CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    requestorId INT NOT NULL,
    timeCreated DATE,
    FOREIGN KEY (requestorId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    available BOOLEAN NOT NULL,
    ownerId INT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    startTime DATE NOT NULL,
    endTime DATE NOT NULL,
    itemId INT NOT NULL,
    userId INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (itemId) REFERENCES Items(id),
    FOREIGN KEY (userId) REFERENCES Users(id)
);